### ISSUE TITLE
Duplicated javaagent when using the version v31 with datadog forwarder

### ISSUE THREAD

**Issue by LEQADA** [DataDog/datadog-lambda-extension#106]
In this PR https://github.com/DataDog/datadog-lambda-extension/pull/86 the behavior of the extension was changed.

was

```bash
export JAVA_TOOL_OPTIONS="-javaagent:$DD_Agent_Jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
```

and now it's 

```bash
export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -javaagent:$DD_Agent_Jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
```

In [the documentation](https://docs.datadoghq.com/serverless/guide/datadog_forwarder_java/?tab=maven#instrument) it suggests to set `JAVA_TOOL_OPTIONS` env variable:

```
JAVA_TOOL_OPTIONS: -javaagent:"/opt/java/lib/dd-java-agent.jar" -XX:+TieredCompilation -XX:TieredStopAtLevel=1
```

But when we do that we get the `JAVA_TOOL_OPTIONS` with a duplicated `javaagent`

```bash
-javaagent:/opt/java/lib/dd-java-agent.jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -javaagent:/opt/java/lib/dd-java-agent.jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1
```

Am I doing something wrong? Is there a new way to set the `javaagent`?

**Comment by astuyve** [comment]
Hi!

Thanks for reaching out. The Datadog Extension and the Datadog Forwarder are mutually exclusive methods of ingesting data into Datadog.
The docs you linked to are for the `datadog forwarder` not the `datadog extension`. The Extension Docs are [here](https://docs.datadoghq.com/serverless/installation/java/?tab=datadogcli).

The script in this library (modified in #86) was updated because `JAVA_TOOL_OPTIONS` is commonly used to set other flags, including compilation flags in #83.

If you're using this library, you shouldn't need to set `-javaagent` at all, as the script will do it.
Thanks!
