### ISSUE TITLE
XRAY TraceId value is missing when using the lambda extension but present when using forwarder

### ISSUE THREAD

**Issue by ddhanak** [DataDog/datadog-lambda-extension#109]
When using the lambda forwarder with tracing active using aws x-ray, the information is being sent as expected. However, when using the lambda extension layer (setting it up using https://github.com/DataDog/datadog-cdk-constructs), the trace id is not being sent. 

Screenshot from a log that is forwarded by the forwarder that includes the XRAY value:

![image](https://user-images.githubusercontent.com/16140109/213567698-9d078bfa-d926-432f-8ddd-7b3a8f09d33c.png)

Screenshot from a log that is sent by the lambda extension that does not include the XRAY value:

![image](https://user-images.githubusercontent.com/16140109/213567621-dc3a4ae8-7e29-4000-a716-598f86852819.png)

Is this something that is handled by the lambda extension?

Thanks!

**Comment by astuyve** [comment]
Hi! Thanks for reaching out. The Datadog Extension reconstructs the Report Log (because we receive logs via the Telemetry API and not stdout). I'm not sure if we have access to the x-ray trace ID in that exact spot, but it's likely possible to reconstruct it. There are also other ways to apply a trace ID here (including using Datadog tracing or using tags).

Would you mind opening a support ticket with our team so we could understand the business context for this? Thanks!
