### ISSUE TITLE
Question about source maps and stack traces

### ISSUE THREAD

**Issue by sawilde** [DataDog/datadog-lambda-extension#119]
Is it possible to upload source maps using the `datadog-cli` and get `datadog` to use that source map to turn a stack trace from minified gobbledygook to something human readable?

eg if I uploaded a source map like this

```
yarn datadog-ci sourcemaps upload ./dist/lambda \
  --service stack-name-lambdafunction \
  --release-version=$BUILD_NUMBER \
  --minified-path-prefix=/
```

and then tagged my services using DD_VERSION and DD_SERVCE that match the source map upload?

NOTE: I have tried the above and it isn't working but I wonder if I am missing something additional or it is not as yet currently possible.

**Comment by tianchu** [comment]
The backend source map feature is currently limited to RUM. No official support for APM or logs yet. Could you include sourcemap with your project and resolve it in the Lambda runtime instead?

**Comment by tianchu** [comment]
@sawilde closing this issue due to the lack of activity and interest from the broader community. Feel free to follow up over slack if resolving sourcemap inside the Lambda runtime isn't an option for you. However, I doubt we will prioritize the backend support in the very near future, unless the level of customer demand increases significantly.
