### ISSUE TITLE
Rate exceeded (toomanyrequests) in public.ecr.aws/datadog/lambda-extension

### ISSUE THREAD

**Issue by pvicente** [DataDog/datadog-lambda-extension#123]
I've had a few failures in CI building our docker image please could you increase the rate?

Message while building our container:

```
Step 13/14 : COPY --from=public.ecr.aws/datadog/lambda-extension:35 /opt/extensions/ /opt/extensions
invalid from flag value public.ecr.aws/datadog/lambda-extension:35: toomanyrequests: Rate exceeded
```

**Comment by kimi-p** [comment]
Hi @pvicente, I looking into how to increase the quota which I do not find a way to increase the rate limiting for ECR. But I do found this troubleshooting post (https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html). 
> Throttling occurs when calls to a single endpoint from a single user exceed a certain threshold over a period of time.
 
Could you follow the AWS ECR's trouble shooting guide and see if that helps? I'm not an CI expert, but I have heard similar rate limiting happened for Docker Hub. Maybe investigate the best practice of resolving this kind of issue would help.

**Comment by pvicente** [comment]
> Hi @pvicente, I looked into how to increase the quota which I do not find a way to increase the rate limiting for ECR. But I do found this troubleshooting post (https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html).
> 
> > Throttling occurs when calls to a single endpoint from a single user exceed a certain threshold over a period of time.
> 
> Could you follow the AWS ECR's trouble shooting guide and see if that helps? I'm not an CI expert, but I have heard similar rate limiting happened for Docker Hub. Maybe investigate the best practice of resolving this kind of issue would help.

Hi @kimi-p thanks for your reply, we are running our CI in CircleCI and probably due to we are using public.ecr.aws, the rate limit happens for all circle ci builds. I don't think I can implement any retry policy with exponential backoff like suggested in [link](https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html) while using the docker directive:

```COPY --from=public.ecr.aws/datadog/lambda-extension:35 /opt/extensions/ /opt/extensions```

Do you have any other idea?

Many thanks

**Comment by kimi-p** [comment]
Hey @pvicente, still wanted to emphasize that I'm no CI expert 😄 , but maybe something like `Enabling Docker Layer Caching`
(https://circleci.com/docs/docker-layer-caching/ ) can help? I think CircleCI folks should be more equipped to answer than I can about this issue since it should be a pretty common question for them.

I've also able to find the quota for ecr (https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html).
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/47579703/222235511-ffd0e41e-b825-4b62-bb18-00ef6fe244a9.png">

This post may help: https://stackoverflow.com/questions/72570095/toomanyrequests-rate-exceeded-only-when-using-docker-pull-from-ecr

If you are using unauthenticated pulling, maybe try pull after authentication may help too. Hope all these would help.

**Comment by pvicente** [comment]
thanks @kimi-p, I've moved the directive to use Docker Layer Caching and avoid these kind of issues. Many thanks!!!
