### ISSUE TITLE
Possible China

### ISSUE THREAD

**Issue by m1rl0k** [DataDog/datadog-lambda-extension#163]
Possible to build this in China aws account, manually? The arns and support are for US and Gov, but whats the possibility of deploying this extension yourself in china; using your own ARN rather than datadogs.

**Comment by IvanTopolcic** [comment]
It's technically possible to build it yourself. You'll need to build the agent binary, and plop it into /opt/extensions where Lambda will be able to execute it. The "layer" is just a zipfile. You can learn more about Lambda layers [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-extensions.html).

**Comment by duncanista** [comment]
Hey @m1rl0k, we currently don't officially support this due to Datadog not operating in China.
As stated above, it's possible to have a workaround to build it yourself. 

I'd suggest contacting our support team through a ticket in our [platform](https://help.datadoghq.com/hc/en-us/requests/new). Your use case is important to us, and we want to make sure you can use Datadog as your desire.

I'm going to close this by now, since it's more of a feature request – which you would help us by creating a support ticket through the platform, since responses might be quicker than here.

If you have any questions or concerns, feel free to re-open this issue!
