### ISSUE TITLE
When will v61 be released with datadog-agent 7.55.x tag?

### ISSUE THREAD

**Issue by colinhoernig** [DataDog/datadog-lambda-extension#325]
Hi there. I am attempting to remediate `CVE-2024-36129`, fixed in datadog-agent 7.55.x release. We rely on `datadog-lambda-extension` but are awaiting tagged release v61 to pull it in without manually overriding versions in dependencies. Is there an expected date this will be tagged so we can complete remediation?

Related context: https://github.com/DataDog/datadog-agent/issues/26403#issuecomment-2223311375

**Comment by purple4reina** [comment]
Hey @colinhoernig, extension [version 59](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v59) contains the fix for [CVE-2024-36129](https://github.com/advisories/GHSA-c74f-6mfw-mm4v) but we had to pull it due to an issue. We're working on a fix now and will get it out as soon as possible.

If you're willing to do some testing on your end, you're welcome to try out v59. Most customers did not have a problem with it. Though we are unable to make any guarantees for how it will work for you, so using v59 isn't something I recommend.

Hope this helps, happy answer any other questions you may have.

**Comment by colinhoernig** [comment]
@purple4reina thank you -- more than willing to try v59 and will give it a try.  I saw that v60 was published as a duplicate of v58 and that there were issues with v59, but I don't mind giving it a try. It might turn out to be effective enough for us until v61 is tagged.

Thank you!

**Comment by colinhoernig** [comment]
@purple4reina looks like v59 is working OK for us and have confirmed the CVE remediated. We will update to v61 when it is released.
