### ISSUE TITLE
Beta extension: Node.js aws.lambda traces not visible

### ISSUE THREAD

**Issue by jokalli2** [DataDog/datadog-lambda-extension#399]
Hello,

We tried the beta extension yesterday. With our Rust lambda it worked perfectly. That has only `opentelemetry_datadog` operation type. Next we tried with a Node.js lambda. It is using `arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Node20-x:115` lambda layer to add the Datadog tracer. After deployment, we no longer saw any requests with `aws.lambda` operation type. When changing the operation type to `http.request`, data was visible.

In the traces view also no traces with the `aws.lambda` operation type, but you could see traces after changing the operation type `http.request`. Interestingly the traces had an `aws.lambda` span.

Are we doing something wrong or is there still some functionality missing?

**Comment by astuyve** [comment]
Hi @jokalli2, thanks for the note!
It should work totally fine with our nodejs tracing layer.

What you're describing seems super strange though, because changing the primary operation type shouldn't affect which spans are created (it's a server-side setting and doesn't affect the tracer).

I'm not able to reproduce this on my own setup, could you open a support ticket and attach this thread? You can use the live chat or email support@datadoghq.com

Thanks!
AJ

**Comment by jokalli2** [comment]
Hello @astuyve , thank you for your response. I opened a support ticket 1864371. I'm closing this ticket.
