### ISSUE TITLE
Encounter log message duplication with DD_EXTENSION_VERSION next

### ISSUE THREAD

**Issue by smg-kayle** [DataDog/datadog-lambda-extension#476]
## Expected Behavior
Logs produced by Lambda function should not be sent to datadog

## Actual Behavior
After adding `DD_EXTENSION_VERSION: next` as lambda function environment variable, I observe 2 log message with the same timestamp, one produced by Lambda function itself and one by the Datadog Log Forwarder

### Logs by the Forwarder
![Image](https://github.com/user-attachments/assets/8e70e160-2b2f-4854-adc0-cc69301a46bd)

### Logs by the Lambda function
![Image](https://github.com/user-attachments/assets/7e7f5ff9-21ce-48bf-8e79-c1813a245114)

### Datadog CDK construct configuration
```typescript
const datadog = new Datadog(scope, 'Datadog', {
      apiKeySecretArn: DATADOG_API_KEY_SECRET_ARN,
      captureLambdaPayload: true,
      enableDatadogLogs: false,
      env,
      version: VERSION,
      injectLogContext: true,
      extensionLayerVersion: 65,
      nodeLayerVersion: 115,
      service: 'service-name',
      site: 'datadoghq.eu',
      enableDatadogTracing: !isDevStage,
    });
```

## Specifications

  - Datadog Lambda Layer version: 64_next, 65_next
  - Node version: 20 LTS

**Comment by duncanista** [comment]
Should be available in the next version `v67` of the Extension!

**Comment by smg-kayle** [comment]
@astuyve @duncanista Tremendously thanks for your quick actions.

Should I leave this open until `v67` is utilized and confirmed it is fixed?

**Comment by duncanista** [comment]
Don't worry about it, we will notify you and close the issue when we create the release (very soon)! 

Thanks for reporting the issue! 🐸

**Comment by duncanista** [comment]
Hey @smg-kayle,

This should have been fixed in the latest release `v67`, please ensure to test this new version in staging/dev environments, as it contains some breaking changes.

For more information, please read about [Next-Gen Datadog Lambda Extension](https://github.com/DataDog/datadog-lambda-extension?tab=readme-ov-file#next-generation-lambda-extension) documentation and the [release notes](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v67).
