### ISSUE TITLE
Support SSM Parameter Store for the DD_AP_KEY

### ISSUE THREAD

**Issue by fatbasstard** [DataDog/datadog-lambda-extension#7]
Instead of only supporting Plaintext or Secrets Manager it would be nice if Parameter Store is also supported for the configuration.

**Comment by fatbasstard** [comment]
@tianchu Any updates on this feature?

**Comment by tianchu** [comment]
@fatbasstard Sorry for the late reply 🙇  We really haven't seen enough interests from other customers, thus no work has been prioritized internally. 

I'm closing this issue because we haven't seen others expressing interests on this issue, despite its been open for almost one year. I assume this isn't a business blocker for you, but if somehow it is, feel free to contact your Datadog CSM to escalate and we can follow up there.

Really sorry I couldn't deliver a better news here, but we do need to invest in most wanted features first. Thanks for your understanding.

**Comment by stekern** [comment]
Support for this was added to the Datadog forwarder in March (see https://github.com/DataDog/datadog-serverless-functions/pull/915, via `DD_API_KEY_SSM_NAME`). To prevent customer confusion, it would be great to have feature parity across the various Datadog components. Any plans to pick this back up for the Lambda extension?
